# Generated by Django 4.0.6 on 2022-10-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_userr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userr',
        ),
    ]
